### PR TITLE
feat: updating AWS Provider and Terraform version

### PR DESCRIPTION
**Pull request by esacteksab**
Changes proposed in this pull request:

- ci: TFDocs official GHA
- chore: removing leftovers from terratest
- ci: updating pre-commit
- feat: upgrading AWS and Terraform versions

This is similar to [this](https://github.com/trussworks/terraform-aws-acm-cert/pull/135) PR.

### CODE REVIEW

**Comment by esacteksab** [comment]
> Why remove the examples?
> 
> Also: Merge conflict! Yay!

Because the examples are remnants that weren't removed when we got rid of terratest. They're not necessary.

**Comment by jsclarridge** [comment]
Regarding the version constraints, Terraform's recommended best practice (https://developer.hashicorp.com/terraform/language/expressions/version-constraints#best-practices) is for reusable modules to only specify a minimum version constraint:

> Reusable modules should constrain only their minimum allowed versions of Terraform and providers, such as >= 0.12.0. This helps avoid known incompatibilities, while allowing the user of the module flexibility to upgrade to newer versions of Terraform without altering the module.

We previously specified maximum versions in several of our modules, but then I think we switched to only specifying minimum versions.

Either way, this is a good candidate for an Architectural Decision Record (ADR).

**Comment by rpdelaney** [comment]
@esacteksab 

> Because the examples are remnants that weren't removed when we got rid of terratest. They're not necessary.

They're used by humans, not just terratest, though :(

**Review by rpdelaney — CHANGES_REQUESTED** [review]
Are the examples out of date? Unhelpful? Worse than nothing? 👀

**Comment by rpdelaney** [comment]
@esacteksab I might be wrong, but from looking at these examples/ that were removed, I don't see an obvious connection to terratest :(

**Comment by esacteksab** [comment]
Sorry, I've neglected this. I'll be back hopefully by EOD tomorrow (June 23, 2023). Thank you and sorry!

**Review by rpdelaney — APPROVED** [review]
YAY :D

Now we get to battle with terraform-docs short circuiting required checks!

**Comment by esacteksab** [comment]
> YAY :D
> 
> Now we get to battle with terraform-docs short circuiting required checks!

Yeah, I have to be honest. That experience sucked. I'd run pre-commit locally, go to push, couldn't because merge conflicts, pull, make changes, attempt to push, couldn't. It was _terrible_ and if this is what it means to have CI do writes on doc updates, then I'm a hard no and I change my mind. I'll never contribute again because it's too terrible, like worse than why I championed to let the machines do stuff for us. Sorry! I was wrong. I'm team get rid of it. /rant

**Review by jsclarridge — CHANGES_REQUESTED** [review]
Given some of the recent commits, I don't think the current changes to the following files are needed:

```
.terraform.lock.hcl
README.md
```

**Pull request closed without merging**
